"""
Multilingual Localization & Regional Accessibility Engine.
Supports English (en), हिन्दी (hi), and मराठी (mr) for HackMatrix 5.0 (PCCOE Pune).
Demonstrates SDG 10: Reduced Inequalities via vernacular financial inclusion.
"""

from typing import Dict, Any

TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "en": {
        "app_title": "Financial Health Copilot",
        "tagline": "SDG-8 & SDG-10 • True Disposable Affordability & Cash-Flow Guard",
        "demo_persona": "Demo Persona:",
        "link_account": "Link Account (AA Sandbox)",
        "aa_active": "AA Stream Active (Linked)",
        "add_expense": "Add Expense",
        "voice_copilot": "Voice Copilot",
        "voice_hint": "Click mic or test: 'Can I afford 5,000?'",
        "monthly_income": "Monthly Income",
        "verified_salary": "Verified salary credit",
        "fixed_obligations": "Fixed Obligations",
        "fixed_desc": "Rent, Car EMI, Insurance",
        "lifestyle_spend": "Lifestyle Spend",
        "lifestyle_desc": "Dining, CC bill, leisure",
        "disposable_surplus": "Disposable Surplus",
        "investable_capacity": "True investable capacity",
        "emergency_buffer": "Emergency Buffer",
        "liquid_savings": "liquid savings",
        "months": "Months",
        "core_innovation": "Core Innovation",
        "affordability_title": "Dynamic Affordability & Buffer Calibrator",
        "affordability_subtitle": "Tests if an investment eats too far into real disposable margin.",
        "proposed_investment": "Proposed Monthly Investment (SIP / Recurring):",
        "remaining_buffer": "Remaining Buffer",
        "buffer_drain": "Buffer Drain",
        "safe_ceiling": "Copilot Calibrated Safe Monthly Ceiling:",
        "expected_impact": "Expected Impact",
        "compound_trajectory": "Compound Growth Trajectory",
        "trajectory_subtitle": "Comparing 12% Equity SIP, 6.5% Conservative Debt, and 0% Cash mattress.",
        "transparency_title": "Explainability Audit & Cognitive Provenance",
        "transparency_subtitle": "Every insight is explicitly classified into observed facts, model predictions, or recommendations.",
        "linked_transactions": "Linked Financial Transactions",
        "transactions_subtitle": "Ingested via simulated Account Aggregator & verified recurring commitments.",
        "action_required": "Action Required",
        "shortfall_alert": "Impending Liquidity Deficit: Shortfall of",
        "cashflow_stable": "Cash Flow Stable for Upcoming 7 Days",
        "chat_title": "FinCopilot Assistant",
        "chat_subtitle": "Ask any question about affordability, upcoming bills, or loans in English, हिन्दी, or मराठी.",
        "chat_placeholder": "Ask: 'Can I afford a ₹30,000 phone on EMI?' or 'Explain my bills'",
        "chat_send": "Send",
        "quick_prompts_title": "Suggested Scenarios:",
        "prompt_chip_1": "Can I afford ₹8,000 SIP?",
        "prompt_chip_2": "Can I buy a ₹40,000 phone on 6-mo EMI?",
        "prompt_chip_3": "Why is my 7-day cash flow at risk?",
        "prompt_chip_4": "What if I cut dining out by 30%?",
    },

    "hi": {
        "app_title": "फाइनेंशियल हेल्थ कोपायलट",
        "tagline": "SDG-8 व SDG-10 • वास्तविक बचत क्षमता व कैश-फ्लो सुरक्षा",
        "demo_persona": "डेमो प्रोफाइल:",
        "link_account": "खाता जोड़ें (AA सैंडबॉक्स)",
        "aa_active": "AA डेटा सक्रिय (सत्यापित)",
        "add_expense": "खर्च जोड़ें",
        "voice_copilot": "वॉइस कोपायलट",
        "voice_hint": "माइक दबाएं या पूछें: 'क्या मैं 5,000 निवेश कर सकता हूँ?'",
        "monthly_income": "मासिक आय",
        "verified_salary": "सत्यापित वेतन जमा",
        "fixed_obligations": "निश्चित देनदारियां",
        "fixed_desc": "किराया, ईएमआई, बीमा प्रीमियम",
        "lifestyle_spend": "जीवनशैली खर्च",
        "lifestyle_desc": "खान-पान, शॉपिंग व मनोरंजन",
        "disposable_surplus": "वास्तविक बचत योग्य अधिशेष",
        "investable_capacity": "सच्ची निवेश क्षमता",
        "emergency_buffer": "आपातकालीन फंड",
        "liquid_savings": "तरल बचत",
        "months": "महीने",
        "core_innovation": "मुख्य नवाचार",
        "affordability_title": "सटीक सामर्थ्य व जोखिम विश्लेषक",
        "affordability_subtitle": "जांचता है कि निवेश आपके सुरक्षा बफर को कितना प्रभावित करता है।",
        "proposed_investment": "प्रस्तावित मासिक निवेश (SIP / आवर्ती):",
        "remaining_buffer": "शेष सुरक्षा बफर",
        "buffer_drain": "बफर उपयोग",
        "safe_ceiling": "कोपायलट द्वारा अनुशंसित सुरक्षित मासिक सीमा:",
        "expected_impact": "अपेक्षित दीर्घकालिक प्रभाव",
        "compound_trajectory": "चक्रवृद्धि विकास प्रक्षेपवक्र",
        "trajectory_subtitle": "12% इक्विटी एसआईपी, 6.5% सावधि जमा व 0% नकद की तुलना।",
        "transparency_title": "पारदर्शिता व व्याख्यात्मक प्रमाण",
        "transparency_subtitle": "प्रत्येक परिणाम को तथ्यों, भविष्यवाणियों व सुझावों में स्पष्ट रूप से वर्गीकृत किया गया है।",
        "linked_transactions": "संबद्ध बैंक लेनदेन",
        "transactions_subtitle": "खाता एग्रीगेटर के माध्यम से सुरक्षित रूप से प्राप्त डेटा।",
        "action_required": "कार्रवाई आवश्यक",
        "shortfall_alert": "आगामी नकदी की कमी: घाटा",
        "cashflow_stable": "आगामी 7 दिनों के लिए नकदी प्रवाह सुरक्षित",
        "chat_title": "फिन-कोपायलट सहायक",
        "chat_subtitle": "सामर्थ्य, आगामी बिलों या ईएमआई के बारे में हिन्दी या मराठी में पूछें।",
        "chat_placeholder": "पूछें: 'क्या मैं ₹30,000 का फोन ईएमआई पर ले सकता हूँ?'",
        "chat_send": "भेजें",
        "quick_prompts_title": "सुझाए गए परिदृश्य:",
        "prompt_chip_1": "क्या ₹8,000 की SIP सुरक्षित है?",
        "prompt_chip_2": "क्या मैं ₹40,000 का फोन 6 महीने की EMI पर ले सकता हूँ?",
        "prompt_chip_3": "आगामी 7 दिनों में नकदी का संकट क्यों है?",
        "prompt_chip_4": "अगर मैं बाहर खाना 30% कम कर दूँ तो क्या होगा?",
    },

    "mr": {
        "app_title": "फायनान्शियल हेल्थ कोपायलट",
        "tagline": "SDG-8 आणि SDG-10 • खरी परवडणारी क्षमता आणि रोख प्रवाह रक्षक",
        "demo_persona": "डेमो व्यक्तीमत्व:",
        "link_account": "खाते जोडा (AA सँडबॉक्स)",
        "aa_active": "AA डेटा प्रवाहित (जोडले)",
        "add_expense": "खर्च जोडा",
        "voice_copilot": "व्हॉइस कोपायलट",
        "voice_hint": "माइक दाबा किंवा विचारा: 'मी ₹5,000 गुंतवू शकतो का?'",
        "monthly_income": "मासिक उत्पन्न",
        "verified_salary": "पगार जमा (सत्यापित)",
        "fixed_obligations": "नियमित देणी",
        "fixed_desc": "घरभाडे, कार हप्ता (EMI), विमा",
        "lifestyle_spend": "जीवनशैली खर्च",
        "lifestyle_desc": "हॉटेलिंग, खरेदी आणि मनोरंजन",
        "disposable_surplus": "खर्च करण्यायोग्य निव्वळ शिल्लक",
        "investable_capacity": "खरी गुंतवणूक क्षमता",
        "emergency_buffer": "आपत्कालीन निधी",
        "liquid_savings": "उपलब्ध शिल्लक",
        "months": "महिने",
        "core_innovation": "प्रमुख वैशिष्ट्य",
        "affordability_title": "परवडणारी क्षमता आणि जोखीम कॅल्क्युलेटर",
        "affordability_subtitle": "गुंतवणूक तुमच्या सुरक्षित शिल्लकेला किती धोका पोहोचवते याची अचूक तपासणी.",
        "proposed_investment": "प्रस्तावित मासिक गुंतवणूक (SIP / नियमित):",
        "remaining_buffer": "उर्वरित सुरक्षित शिल्लक",
        "buffer_drain": "बफर वापर",
        "safe_ceiling": "कोपायलटने शिफारस केलेली सुरक्षित मासिक मर्यादा:",
        "expected_impact": "अपेक्षित संपत्ती वाढ",
        "compound_trajectory": "चक्रवाढ वाढीचा आलेख",
        "trajectory_subtitle": "12% इक्विटी एसआयपी, 6.5% बँक मुदत ठेव आणि 0% रोख यांची तुलना.",
        "transparency_title": "पारदर्शकता आणि डेटा पुराव्याची पडताळणी",
        "transparency_subtitle": "प्रत्येक निष्कर्ष तथ्य, अंदाज किंवा शिफारस म्हणून स्पष्टपणे दाखवला जातो.",
        "linked_transactions": "जोडलेले बँक व्यवहार",
        "transactions_subtitle": "खाते अ‍ॅग्रीगेटरद्वारे थेट आणि सुरक्षितपणे जोडलेले.",
        "action_required": "तातडीची कृती आवश्यक",
        "shortfall_alert": "संभाव्य पैशांची टंचाई: तूट",
        "cashflow_stable": "पुढील 7 दिवसांसाठी रोख प्रवाह सुरक्षित",
        "chat_title": "फिन-कोपायलट सहाय्यक",
        "chat_subtitle": "परवडणारी क्षमता, आगामी बिले किंवा कर्जाबद्दल मराठी, हिंदी किंवा इंग्रजीत विचारा.",
        "chat_placeholder": "विचारा: 'मी ₹30,000 चा फोन ईएमआय वर घेऊ शकतो का?'",
        "chat_send": "विचारा",
        "quick_prompts_title": "उदाहरणे (क्लिक करा):",
        "prompt_chip_1": "मी ₹8,000 ची SIP करू शकतो का?",
        "prompt_chip_2": "मी ₹40,000 चा फोन 6 महिन्यांच्या EMI वर घेऊ का?",
        "prompt_chip_3": "पुढील 7 दिवसांत पैशांची तूट का होणार आहे?",
        "prompt_chip_4": "जर मी हॉटेलिंग 30% कमी केले तर किती बचत होईल?",
    }
}


def get_translations_for_lang(lang: str = "en") -> Dict[str, str]:
    """Returns translation dictionary for requested language code (defaults to en)."""
    return TRANSLATIONS.get(lang.lower(), TRANSLATIONS["en"])


def get_speech_config(lang: str = "en") -> Dict[str, Any]:
    """Returns Web Speech API synthesis configurations for native accent."""
    configs = {
        "en": {"code": "en-IN", "rate": 1.0, "pitch": 1.0},
        "hi": {"code": "hi-IN", "rate": 0.95, "pitch": 1.0},
        "mr": {"code": "mr-IN", "rate": 0.95, "pitch": 1.0}
    }
    return configs.get(lang.lower(), configs["en"])
